slic3r/Slic3r

lib/Slic3r/GUI/BonjourBrowser.pm, lib/Slic3r/GUI/Tab.pm
I've added a routine to the Bonjour code to get the port, and changed the relevant code in Tab.pm to make use of it.
=> A partial fix for issue #2530

lib/Slic3r/GUI/Tab.pm
Here's a simple fix for #2526. Tested it too :D
=> Fix for issue #2526, changed to GET.

README.md, lib/Slic3r/Config.pm, lib/Slic3r/Print/GCode.pm, slic3r.pl, utils/zsh/functions/_slic3r, xs/src/libslic3r/GCodeWriter.cpp, xs/src/libslic3r/GCodeWriter.hpp, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp, xs/t/15_config.t, xs/xsp/GCodeWriter.xsp
See https://github.com/alexrj/Slic3r/issues/2505
=> added support Machinekit flavour GCode

xs/src/libslic3r/GCode.cpp
=> Bugfix #3038

xs/src/libslic3r/GCodeSender.cpp
Signed-off-by: Gregor Best <gbe@unobtanium.de>
=> Implement serial port baudrate selection for OpenBSD

utils/post-processing/fan_kickstart.py
Addresses #3308
Post-process script that inserts a M106 S255 command in front of another M106 command.
=> Post process script for fan kickstart

lib/Slic3r/GUI/Plater/ObjectCutDialog.pm
Fixes a performance issues on Windows, where the cut is being
refreshed many times for a single move of the Z plane.
Fixes a problem on Windows, where the new wxWidgets always returned
Cancel, even if the window was closed with the "Cut" button.
Improved performance if the live preview is disabled or not needed,
because both top and bottom parts shall be displayed.
Closes #3359
Originally proposed by @bubnikv
=> Performance fixes for plater cut.

.github/CONTRIBUTING.md
New notes for contributing new code via PRs to Slic3r and feature requests. Hopefully this helps.
=> Added notes about pull requests and internal preview

utils/package_win32.ps1
Missing a file for the CI server to be able to produce builds of master that nontechnical people can use. Fixes #3469.
=> added libglut dll from strawberryperl

lib/Slic3r/GUI/Plater/2D.pm
on Linux/GTK.
Cherry-picked from prusa3d/release_1_3_branch. Thanks to @bubnikv
=> 2D platter rendering fixed on Windows, and the background color fixed

xs/src/libslic3r/Config.cpp, xs/src/libslic3r/Config.hpp
Moved new deserialize functions (and their accompanying boost dependencies) into Config.cpp from Config.hpp.
Fixes #3539
=> Fix/workaround for Boost issues in Config.hpp

xs/src/libslic3r/GCode.cpp, xs/src/libslic3r/GCodeWriter.cpp
=> Pair of fixes for temperature standby on MB-derived FW

lib/Slic3r/GCode.pm, xs/src/libslic3r/GCodeWriter.cpp
Fix that references Sailfish and MakerWare set temperature and wait issue #3546
=> Sailfish temps fix

lib/Slic3r/Fill.pm, lib/Slic3r/Fill/Rectilinear.pm, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp
Fixes #3225 with a new fill option called 'Aligned Rectilinear'
=> Aligned rectilinear infill

lib/Slic3r/GUI/Tab.pm
Implements #3571, thank you @bubnikv
=> New feature: Propose to enable "detect bridging perimeters"

README.md, slic3r.pl, t/gcode.t, utils/zsh/functions/_slic3r, xs/src/libslic3r/GCodeWriter.cpp, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp
=> Added Repetier FW flavor, fixed accel gcode generation for it.

lib/Slic3r/GUI/Plater.pm
=> Add LWP::UserAgent to use of plater.pm

xs/src/libslic3r/PrintObject.cpp
I always prefer to avoid adding new options, so I'd rather try to find a decent heuristic for avoiding bridge over infill when not necessary.
Overstuffing was mostly handled by 38a9e32a287c4a601e256ebd96533f68c0c8dcc0 and 4724f0fb99abee2fa1b3252c4137e738f760e7d6.
The main issue now is to avoid bridging in those cases when it's physically possible but not necessary.
I'm proposing a new logic which compares infill density to a density threshold, above which we don't bridge. We calculate this density threshold by comparing the bridge flow to the normal solid infill flow we would use otherwise. If those flows are almost equal, we set the threshold to 25% (i.e. we only bridge when printing at low densities). If normal flow would be much lower, thus very poor (this happens when printing thin …
=> Limit bridge over infill

lib/Slic3r/GUI/BedShapeDialog.pm
=> Catch input that resolves to 0 in bed shape dialog

lib/Slic3r/GUI/3DScene.pm
Replace glVertexPointer_p() call with glVertexPointer_c(), 
Delete VBO buffers after they've been drawn. Both ways work on OpenGL.pm 0.7
Credit to @bubnikv from prusa3d fork, drawn from commit prusa3d@c0b3de6248f6e6d50624b3d2132c823fb65af95e.
Switch HAS_VBO = 0 in 3DScene.pm to not use VBOs.
=> OpenGL.pm fixes

lib/Slic3r/GUI/Tab.pm, lib/Slic3r/Print/GCode.pm, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp
Addresses #3309 
Handles multiple extruders as well.
=> Filament-specific start and end gcode.

xs/src/libslic3r/Print.cpp, xs/src/libslic3r/SLAPrint.cpp
change auto_ptr to unique_ptr
Fixes : #3702
=> remove deprecated code and add new one

lib/Slic3r/GUI/3DScene.pm, lib/Slic3r/GUI/MainFrame.pm
* Follow the OpenSCAD convention:
* Reorder the items
* Rename Rear -> Back and Iso -> Diagonal (Iso stands for a projection, not
for a view -- upcoming versions could have isometric/prespective views...)
* Assign accels from 4 to 0
=> Add accelerators (keyboard shortcuts) to View menu

xs/src/admesh/stlinit.c
=> Abort loading if the file size is larger than the header facets

package/win/compile_wrapper.ps1, package/win/package_win32.ps1, package/win/shell.cpp, xs/t/22_exception.t
=> force --gui for shell during compilation if -DFORCE_GUI is set

translation/fr_FR.po
Hi there
My two cents
I read somewhere that we keep sticking with PR for now, so here it is
I'm not used to POedit so I hope I didn't mess too much
=> [i18n] French translation

lib/Slic3r/Config.pm
straight value of 0 is illegal.
=> Validate support material threshold in Config.pm

translation/en_US.po, translation/fr_FR.po, xs/src/libslic3r/PrintConfig.cpp
this fixes #3846 - this is my very first attempt so check it out.......
=> I18n - fix for #3846

.travis.yml, appveyor.yml, package/deploy/sftp.sh, package/deploy/winscp.ps1, package/linux/travis-decrypt-key
Fixes Travis for pull requests not coming from alexrj/Slic3r
=> only decrypt if the key is available

package/deploy/sftp.sh, package/deploy/winscp.ps1, package/linux/make_archive.sh
Fixes build server (pull requests from same repo were going to master branch dev folder)
=> Deploy PRs to branches/ subdir.

translation/zh_CN.po
This is my very first attempt for pull request.
I was not so sure about some of the translations, which I have marked.
So, check it out please.
=> [PULL REQUEST]Add translation/zh_CN.po

lib/Slic3r/Print/Object.pm, lib/Slic3r/Print/SupportMaterial.pm, t/support.t
There are inconsistent rare crashes which I cannot find as related to my changes.
Fixes #3836
=> Addressed logic of enforced supports. 

translation/de_DE.po
Been a while since I've done anything in German, but it's a start.
=> Add Translation de_DE.po

lib/Slic3r/GUI/3DScene.pm, lib/Slic3r/GUI/MainFrame.pm, lib/Slic3r/GUI/Plater.pm, lib/Slic3r/GUI/Plater/2DToolpaths.pm, slic3r.pl
=> Adding Zoom

appveyor.yml, package/win/appveyor_buildscript.ps1, package/win/appveyor_preinstall.ps1, package/win/package_win32.ps1
Reworked Windows build scripts to produce 32bit and 64bit builds.
=> Windows 32-bit build.

package/linux/libpaths.txt, package/linux/startup_script.sh
=> Linux build

package/linux/appimage.sh
=> Fix Version= key

README.md
=> Add 3mf format to readme.md 

lib/Slic3r/GUI/Plater.pm
Ensure that with autocenter turned off the part is not positioned
in the center of the bed.
=> Fix to autocenter option.

lib/Slic3r/GUI/Plater.pm
With the change to the autocenter option, its possible that the object could be outside the plater. This might not be noticed so provide a warning message.
=> Provide warning when object(s) are outside print bed.

xs/src/admesh/portable_endian.h
As requested, create a pull request of my change:
Fix compiling at least for FreeBSD 11+
=> Fix compiling for FreeBSD

lib/Slic3r/GUI/3DScene.pm
=> Fixes the GL_MULTISAMPLE and GL_ARRAY_BUFFER_ARB fail to launch

t/adaptive_slicing.t, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintObject.cpp
=> Removed factor 4 from layer height gradation + comments + minor stuff

xs/src/libslic3r/Fill/Fill3DHoneycomb.cpp
If the print alternates between horizontal and vertical at each square, it is able to print a fully-supported honeycomb structure with half as much filament and only sweeping through one direction. I was mostly there with the initial implementation of this code, but I needed to do some large octahedron printing myself to work out a better way to do it.
This modification reduces the need for bridging in the infill pattern (it only happens at the squares at the top and bottom of the print), which increases strength and reduces fill density.
see issue #4045 for more details.
FWIW, Slic3r has been much easier to hack than Cura2. Thanks for writing code that will compile somewhat easily on a Debian system.
=> Update 3D Honeycomb Infill to switch directions at squares rather than every line

package/linux/startup_script.sh
with spaces, or from a desktop shortcut.
Patch too simple to create a branch, sorry
=> Now work as startup script from every directory, also if runt from a link in /usr/bin, 

lib/Slic3r/GUI/Plater.pm
Changed variable_layer_height icon from cog.png to variable_layer_height.png.
=> Changed variable_layer_height icon

lib/Slic3r/GUI/Preferences.pm
Always had to tinker with the `Preferences.pm` because of merge conflicts.
Added comment to each `$optgroup->append_` group to be unique => no more merge conflicts with preferences.
=> Added comments to avoid merge conflicts.

xs/src/libslic3r/Fill/Fill.cpp, xs/src/libslic3r/Fill/FillGyroid.cpp, xs/src/libslic3r/Fill/FillGyroid.hpp, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp
Gyroid infill.
Same version than in the PE.
#3666
=> gyroid infill

lib/Slic3r/GUI/Plater.pm
Fixes #4439 introduced in #4424.
=> Moved resetting parameter of thumbnail generation to on_thumbnail_made

lib/Slic3r/GUI/PresetEditor.pm, lib/Slic3r/Print/GCode.pm, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp, xs/src/libslic3r/PrintGCode.cpp
Add a placeholder [filament_extruder_id], which is valid in Filament custom gcode and refers to whatever extruder it is loaded into. 
Also revert filament_settings_id.
#4569
=> Add [filament_extruder_id] and revert work done for [filament_settings_id]

package/osx/make_dmg.sh, package/osx/plist.sh
=> Improvements to make_dmg.sh

slic3r.pl
See https://bugzilla.redhat.com/show_bug.cgi?id=1661324
and https://trac.wxwidgets.org/ticket/17702
=> Run on X11, as Wayland crashes Slic3r

.travis.yml, package/common/util.sh, package/linux/appimage.sh, package/linux/make_archive.sh, package/linux/startup_script.sh, package/linux/travis-deploy-main.sh
The packaging script isn't finding perl (so it can't include it). 
Fixes #4635
=> Update packaging script to be more intelligent

lib/Slic3r/Config.pm, lib/Slic3r/GUI/Plater/SplineControl.pm, lib/Slic3r/GUI/PresetEditor.pm
=> Fix division by zero when min=max layer heights

package/deploy/sftp-symlink.sh, package/deploy/sftp.sh, package/deploy/winscp.ps1, package/osx/make_dmg.sh, package/win/package_win32.ps1, src/test/libslic3r/test_print.cpp, xs/src/libslic3r/PrintObject.cpp
Update deployment scripts to do cleanup of old branch builds
=> Cleanup old branch builds

src/test/libslic3r/test_skirt_brim.cpp, src/test/test_data.hpp, xs/src/libslic3r/Print.cpp, xs/src/libslic3r/Print.hpp, xs/src/libslic3r/PrintGCode.cpp
I've finished porting the tests from `t/skirt_brim.t` and found/fixed some bugs along the way.
=> Fix skirt/Brim

README.md
I won't explain why I'm making these suggestions unless I'm asked. I think they are self-explanatory ;)
=> README.md:grammar improvement suggestions [skip ci]

xs/src/libslic3r/LayerRegionFill.cpp
=> Apply fix proposed by @supermerill for #4289

lib/Slic3r/GUI/Plater.pm
fixes https://github.com/slic3r/Slic3r/issues/4758
=> Show estimated printing time after exporting gcode

package/linux/libpaths.appimage.txt
=> Add libcrypt.so.1 to appimage.

xs/src/libslic3r/TriangleMesh.cpp
=> Use admesh's stl_repair() instead of simulating it ourselves.

lib/Slic3r/GUI/Plater.pm
PR to finalize the incomplete renaming from #4590.
=> finalize renaming from 'extended_gui' to 'rotation_controls'

lib/Slic3r/Print/GCode.pm, src/test/libslic3r/test_printgcode.cpp, xs/src/libslic3r/PrintGCode.cpp
This PR is for #4637.  It looked like #4688 had gone stale.  I didn't see any tests for the GUI part of the code but I can add one if you point me in their direction.
=> Set extruder before start gcode

lib/Slic3r/GUI/PresetEditor.pm, xs/src/libslic3r/GCodeWriter.cpp, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp
=> Allow fan to be specified from 0-100 (decimal) instead of 0-255

lib/Slic3r/GUI/Plater.pm
Commits to revolve issue #4588 : Settings dialogs are opened multiple times
=> add new hash to save dialog ref and also a function to show the dialog

lib/Slic3r/Print/GCode.pm, src/test/libslic3r/test_gcode.cpp, src/test/libslic3r/test_printgcode.cpp, xs/src/libslic3r/GCode.cpp, xs/src/libslic3r/GCode.hpp, xs/src/libslic3r/PrintGCode.cpp, xs/xsp/GCode.xsp
Hi, I have prepared edits that calculates COG (center of gravity) based on filament extrusion. Output of that COG is in gcode as a comment
=> calculation of COG in Slic3r

src/GUI/OptionsGroup.hpp, xs/src/admesh/shared.c, xs/src/admesh/stlinit.c, xs/src/libslic3r/ConfigBase.cpp, xs/src/libslic3r/GCode.cpp, xs/src/libslic3r/Model.cpp, xs/src/libslic3r/TriangleMesh.cpp, xs/src/xsinit.h
Implemented changes mentioned in #5042. Removed null checks before calls to delete or free since both are null safe.
=> Removed null checks before calls to delete and free

lib/Slic3r/Print/Simple.pm, slic3r.pl
and their correspondent implementation and documentation
I previously created issue #4862 to submit this change
=> add --rotate-x and --rotate-y to slic3r.pl command line parsing
