slic3r/Slic3r

README.md
Hello !
I suggest using `perl Build.PL --sudo` instead of `sudo perl Build.PL` in the README file.
The rationale being twofold:
* running `sudo perl Build.PL` leaves root-owned files in your local repository, if that is owned by a regular user it might be cumbersome to e.g. clean afterwards.
* for security purposes it's IMHO better to run only parts of the process with elevated privileges instead of the whole one
what do you think ?
Thanks for Slic3r btw :)
=> I suggest using "perl Build.PL --sudo" instead of "sudo perl Build.PL" in the README file.

xs/src/libslic3r/Config.hpp
For some reason, Yosemite handles iostream `>>` number parsing differently than other platforms. Here's a demonstration:
```cpp
#include <stdio.h>
#include <limits>
#include <iostream>
#include <sstream>
int main( ) {
double x = 0;
double y = 0;
std::string point_str("4x5");
std::istringstream iss(point_str);
// Gives "0,0" on Yosemite, current Slic3r implementation
iss >> x;
iss.ignore(std::numeric_limits<std::streamsize>::max(), 'x');
iss >> y;
std::cout << x << "," << y << std::endl;
iss.clear();
iss.str(point_str);
x = 0;
y = 0;
// Works on Yosemite (and others)
std::string coord_str;
if (std::getline(iss, coord_str, 'x')) {
std::istringstream(coord_str) >> x;
if (std::getline(iss, coord_str, 'x')) {
std::istringstream(coord_str) >> y;
}
}
std::cout << x << "," << y << std::endl;
} …
```
=> Use std::getline to deserialize point list coords, fixes #2318

xs/Build.PL
Typemap (Singluar) version 1.00 is essentially identical to Typemaps (Plural)
Typemap is literally a dumb subclass of TypeMaps, and so this
dependency simply gives an extra installation requirement that does
nothing.
See how all of the below are basically just `package Foo; @ISA = Foos ` 
https://metacpan.org/source/SMUELLER/ExtUtils-Typemap-1.00/lib/ExtUtils/Typemap.pm
https://metacpan.org/source/SMUELLER/ExtUtils-Typemap-1.00/lib/ExtUtils/Typemap/InputMap.pm
https://metacpan.org/source/SMUELLER/ExtUtils-Typemap-1.00/lib/ExtUtils/Typemap/OutputMap.pm
https://metacpan.org/source/SMUELLER/ExtUtils-Typemap-1.00/lib/ExtUtils/Typemap/Type.pm
=> Remove redundant dep on ExtUtils::Typemap

xs/src/admesh/stlinit.c
Also added another NULL check for safety. This is to fix a warning provided by gcc 4.9.1
While the reopen *should* be safe, weird things can still happen so we shouldn't assume that it is safe (or that the fp is the same).
=> Fix a warning about unused return value when using freopen in admesh.

lib/Slic3r/Print/Object.pm
This fixes an issue where the support material doesn't honour a custom first
layer extrusion width.
Fixes: #2662
=> Fix support material first layer extrusion width

lib/Slic3r/GUI/Plater/2D.pm
Wx::DrawLine wasn't happy with a polyline, so we pass the sequence of points to Wx::DrawLines
=> Bugfix: correctly draw circular beds in the 2D plater

lib/Slic3r/GUI/Plater.pm
The consumers of filament_presets expected an array index.
=> Fixes #2858

xs/src/libslic3r/GCodeWriter.cpp
Those were swapped during transition to XS.
http://reprap.org/wiki/G-code#M140:_Set_Bed_Temperature_.28Fast.29
http://reprap.org/wiki/G-code#M190:_Wait_for_bed_temperature_to_reach_target_temp
=> Fix incorrect comments to bed temperature setting gcode

lib/Slic3r/GUI/Tab.pm
support_material_enforce_layers works independently of the support_material ||
raft options, so we should not disable the field when support material
generation is disabled.
Fixes: #3046
=> Don't toggle support_material_enforce_layers field

lib/Slic3r/GUI/AboutDialog.pm, lib/Slic3r/GUI/Projector.pm
fixes #2881 by replacing wxCLOSE button by wxOK
=> Fix Slic3r crash when opening About dialog

xs/src/libslic3r/Point.hpp
if BOOST_VERSION < 106000 always succeeds because BOOST_VERSION is
undefined.  In order to avoid the code for new boost, we need <boost/version.hpp>
Before adding the fix, verified that this was the issue with:
#ifndef BOOST_VERSION
#error BOOST_VERSION not defined
#endif
I'm compiling on Windows with Boost in C:\dev\boost_1_60_0
=> Fix issue with undefined BOOST_VERSION

lib/Slic3r/GCode/CoolingBuffer.pm, t/cooling.t, xs/src/libslic3r/GCode.cpp, xs/src/libslic3r/GCode.hpp, xs/xsp/GCode.xsp
The recent GCode writer changes which put the speed changes on a line of
their own have caused the layer time slowdown to be ignored by the regex
in CoolingBuffer.pm.
=> Fix layer cooldown time

lib/Slic3r/GUI.pm, lib/Slic3r/GUI/MainFrame.pm, lib/Slic3r/GUI/Preferences.pm, lib/Slic3r/GUI/Tab.pm, slic3r.pl
The "controller" tab and the settings of the USB/serial connection was
made configurable. Now one may hide the "controller" tab and the USB/serial
connection configuration from the preferences. This is useful for someone,
who never connects his printer to the computer by a cable.
This feature was proposed by Josef Prusa of Prusa3D.
=> allow to hide the "controller" tab

xs/src/libslic3r/GCode.cpp, xs/src/libslic3r/GCodeWriter.cpp, xs/src/libslic3r/GCodeWriter.hpp
The cooling markers were being passed into GCodeWriter::set_speed() as a
comment which were being ignored if gcode_comments was false.
Fixes: #3325
=> Fix cooling not working if !gcode_comments

lib/Slic3r/Print/GCode.pm
This fixes an issue where F0 moves arise from 0-width (or 0 layer height?) support material segments when using autospeed.
Fixes: #3261
=> Don't use equality comparisons for floats

xs/src/libslic3r/GCode.cpp
Appears to fix seam randomness for external perimeters, but holes are still not random enough.
=> Fix for #3069

utils/modifier_helpers/solid_layers.scad
Generate a model that describes layers for incorporation as a modifier mesh. Parameters are in the OpenSCAD script. 
Main improvement I could see to this is porting it to OpenJSCAD so we can take advantage of the editable boxes.
=> Added a short OpenSCAD utility

README.md, lib/Slic3r/Config.pm, slic3r.pl, xs/src/libslic3r/GCode.cpp, xs/src/libslic3r/GCodeWriter.cpp, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp
Avoids resetting extrusion axis after firmware retract (still resets after unretract) with smoothieware.
=> Adds Smoothieware flavor to Gcode

lib/Slic3r/GUI/Tab.pm, lib/Slic3r/Print/Object.pm
Also ensured that support is disabled if spiral_vase is on.
Added a secondary check to make sure that clip_fill_surfaces does not run if we're in spiral_vase.
Fixes #3126
=> infill_only_where_needed is incompatible with spiral_vase: enforced.

lib/Slic3r/Fill.pm
There probably should be a change to the tooltip stating the possible dangers (overextrusion from too thick layer heights). 
Fixes #1783
=> Infill combine, fix #1783

.travis.yml
Fixes #3345 and replaces #3395 Thanks to @hyperair for investigating this.
=> Set LDLOADLIBS to get the linker switch to occur in the right place.

lib/Slic3r/GUI/3DScene.pm, lib/Slic3r/GUI/Plater/2DToolpaths.pm
Cherry-picked the changes into their own branch for clean merging. What follows below is the original post (#3343)
https://github.com/alexrj/Slic3r/files/295253/Patches.zip is required to test/view MSAA with wxWidgets 3.0.3
------------------
This patch improves rendering of the 3D scenes. The improvement is significant on the 3D path simulation.
1) Increases resolution of the depth buffer from 16 bits to 24 bits. 16 bits cause some jagged lines at the intersection of triangles. I believe the computers offering a 16 bit depth buffer only are already in the landfill.
2) Enables multi sample anti aliasing. This is finally supported by wxWidgets 3.1 (February 29, 2016) and the OpenGL support for creation of anti aliased windows has been back ported to wxWidgets 3.0.3 (currently in beta …
=> Support multi sampled anti-aliasing with wxWidgets 3.0.3.

.travis.yml
Back to using packages, root cause had been that a new dependency was added with the cppsvg branch.
=> Add boost-filesystem to list of dependencies

lib/Slic3r/GUI/2DBed.pm, lib/Slic3r/GUI/BedShapeDialog.pm
was defined with an STL.
Fix of rendering on Windows, refresh on resize.
Fixes #3357
Cherrypicked from prusa3d, thanks to @bubnikv
=> Fix of a crash when the Print Bed dialog is reopened after the bed shape

README.md
Goal of these changes is to give people who are interested in helping out constructive pathways to channel their effort and point out task lists. I'm not particularly tied to the wording
Also added qualifier regarding @alexrj 's presence in #reprap and #slic3r, we get a lot of people in the channel looking for him and I feel it is better to manage expectations and point them to someone else who is actively on the team. Hopefully less frustration. 
We've also largely gone to using the issue tracker as one of the main forms of communication about Slic3r and discussing things. I feel that this works in general given people's schedules.
=> Expanded/updated 'how can I help' section to include wiki entries

README.md
sudo/cpanminus is dangerous to the package systems on debian/ubuntu systems.
=> Changed README.md build instructions to point instead to wiki.

lib/Slic3r/GUI/MainFrame.pm
If the "Controller" tab was not visible (disabled from preferences), then the menu items and their shortcuts opened the wrong tab.
Also, the controller tab was not visible if the plater tab was not visible too.
=> Fixed a bug with the "Window" menu items.

lib/Slic3r/GUI/MainFrame.pm
Fix for #3116 , probably the first issue I also had with Slic3r when learning the settings!
`Wx::ToolTip::SetAutoPop()`  is supposed to accept long integer values in milliseconds, though some bug doesn't allow long values, so the biggest int is entered that makes tooltips dissapear after 32 seconds.
I couldn't find a more appropriate place to enter the code, so I entered it in MainFrame.pm
=> Set the tooltip display timer to the max accepted value

xs/MANIFEST, xs/t/22_exception.t, xs/xsp/XS.xsp
Unit test to verify whether Slic3r would hang when croaking from a C++ exception handler. This is an unfortunate error in some Strawberry Perl distributions.
Provided by @bubnikv
=> Add unit test to pre-emptively check for Slic3r hangs (thanks Strawberry Perl!)

lib/Slic3r/GUI/3DScene.pm
I have faced the following problems while navigating in the 3d view:
- I can only move the center of rotation on the X-Y plane so inspecting tall objects is strange.
- I cannot see the center of rotation.
- Sometimes when I want to rotate the view I accidentally move around objects, especially when zoomed in and there is not much free space in the view.
- While moving and rotating the view I have set the center of rotation far far away from the platter and cannot find it any more! Adding an object to the platter resets the view.
This PR adds the following functionality:
- Using the Alt key as modifier one can click and move the camera on the Z axis. This allows for rotating the view around any point in 3d space.
- Added a small indicator for the 3 axes that appears only when rotating or …
=> 3D Navigation improvement features

xs/Build.PL, xs/src/libslic3r/PlaceholderParser.cpp, xs/src/libslic3r/libslic3r.h, xs/src/xsinit.h
Updated xs/Build.PL to understand BOOST_LIBRARY_PATH and
BOOST_INCLUDE_PATH environment variables. This way one may easily
switch between various boost builds.
Some minor tweaks were done to make Slic3r compile with
Visual Studio 2013.
Addresses #3473 
Contributed by @bubnikv
=> Updated xs/Build.PL to support Visual Studio compiler suite.

lib/Slic3r/GUI/3DScene.pm
Addresses #3540
The actual crash case appears to be the bed_triangles and bed_grid_lines draw code. I didn't dive into the exact nature of the segfault, but it can be avoided by explicitly generating buffer objects and doing the necessary binds before the draw command.
Going to do another round of code cleanup and refactoring to make things less messy, PR is intended for a squash+merge at the end. 
TODO: abstract out the draw code slightly and add branching based on whether or not we have Vertex Buffer Objects or not (which is probably the case)
=> Fix for OpenGL.pm 0.70 segfault

xs/src/libslic3r/ExtrusionEntity.cpp
Work from @bubnikv to support splitting loops in the middle of a segment instead of requiring it to be on vertex.
This commit lays some groundwork for the ability to more intelligently place seams.
Also some optimizations in the use of std::swap() to use the move semantics where able.
=> Fix in splitting the loop at a new point.

README.md, lib/Slic3r/Print/Simple.pm, slic3r.pl
Don't arrange the objects on the build plate. The model coordinates
define the absolute positions on the build plate.
The option --print-center will be ignored.
Also there is a fix in the command line invocation of --duplicate-grid
so it will run, but still there is something broken there and the results
are not correct.
Provided by @bubnikv 
Fixes #3493
=> New command line option: --dont-arrange #3493

lib/Slic3r/Fill.pm
Uses the correct layer height for the surface.
Fixes #1783 #2693
=> Calculate actual flow for later inclusion as a ExtrusionPath for internal flow.

xs/src/xsinit.h
Should fix remaining compile issues on Windows.
Fixes #3583
=> Fix perl redefining multiple functions used by boost

lib/Slic3r/GUI/3DScene.pm
Defensive coding - fix provided by @jreinam
Fixes #3589
=> Avoid recentering viewport if the bounding box is max size 0

utils/package_win32.ps1
fixes the naming scheme for the packager for the Appveyor build environment (which apparently needs a slightly different regex)
Fixes #3633
=> Minor revisions/updates for win32 packager

lib/Slic3r/GUI.pm
It causes more problems than it solves, especially with the new slice-on-preview code available.
Most of the weird crash bugs in Slic3r can usually be traced to background processing and strange timing issues that are very very difficult to reproduce.
=> Disable background processing by default.

lib/Slic3r/GCode/PressureRegulator.pm
This solves #3282. It resets the print speed after a advance/discharge and it checks if the speed is unchanged, but an advance has to be made because a discharge was done before.
Please note, this is my first own coding acitivity at github and I'm not familiar with perl, only a little bit of C. If some informations are missing for the request, please let me know!
=> Pressure advance overrides print speeds patch

lib/Slic3r/Print.pm
from .tmp suffix to a non .tmp file on localized Windows, thanks @bubnikv
=> Fixed a bug in renaming a G-code at the end of a G-code export

package/win/compile_wrapper.ps1, package/win/package_win32.ps1, package/win/shell.cpp, package/win/slic3r.rc
Original shell courtesy of @bubnikv. 
This will be merged after I get the build server behaving itself (using perl 5.18-x64 instead of 5.24-x32).
Slic3r dependency archive (x64) -- all of the Perl modules needed to build Slic3r in one handy archive.
https://bintray.com/lordofhyphens/Slic3r/download_file?file_path=slic3r-perl-dependencies-5.18.0-win-x64.7z
=> Added windows shell and script

xs/Build.PL
From what I can tell, if you're building Boost from source on OSX and set it to be static, the output files will not have a version tag in their extension (the .a files). The boost check in Build.PL requires the version to be in the regex (+). This will match zero or more (*) instead.
=> Permit boost libraries to not have the version # in their name

.gitignore, package/deploy-bintray.sh, package/osx/make_dmg.sh, package/osx/plist.sh, package/osx/startup_script.sh
Thanks to @bubnikv who provided his sample scripts to build and package. The new local-lib arrangement obviated the need for most of the complexity but the dmg generation was a good model to write my own. 
Should work anywhere that has a working, statically-linked perl. Build server output is OSX 10.9, perl 5.24 (perlbrew).
I don't currently have a test case on a system that isn't the build server.
(next part is getting the build server itself going automagically)
=> package Slic3r for OSX post-build.

lib/Slic3r/GUI/Plater.pm, lib/Slic3r/GUI/Tab.pm, lib/Slic3r/Print/GCode.pm, lib/Slic3r/Print/Object.pm, xs/src/libslic3r/Extruder.cpp, xs/src/libslic3r/Extruder.hpp, xs/src/libslic3r/Print.hpp, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp, xs/xsp/Extruder.xsp, xs/xsp/Print.xsp
Parking PR here to get feedback, this has been asked for a couple times.
Fixes #647
Fixes #2250 
#1766
=> Add weight/cost output to gcode. On the way to #647

lib/Slic3r/GUI.pm, lib/Slic3r/GUI/3DScene.pm, lib/Slic3r/GUI/Plater/2DToolpaths.pm, lib/Slic3r/GUI/Preferences.pm
The first commit makes mouse-wheel zooming act the same across the 2D and 3D views. Up zooms in, down zooms out (same as OpenSCAD, Inkscape, KISSlicer, web browsers etc).
Then, for those who prefer zooming to go in the opposite direction, there is now a GUI preference to invert the direction (zoom direction like Meshlab, don't know what else).
=> Fix #2861, provide consistent mouse-wheel zoom direction, plus a GUI preference to invert

lib/Slic3r/GUI/Tab.pm, lib/Slic3r/Print/SupportMaterial.pm, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp
Sets the default as well to 60% (as stipulated by https://github.com/alexrj/Slic3r/wiki/Support:-Requirements)
Extends #2098 
Fixes #2068
Using test case from #2068 and setting value to new default:
The option is only considered for auto threshold angle.
=> Configurable overhang threshold as function of perimeter width

xs/src/libslic3r/Flow.cpp
(avoid absurdly wide traces at small layer heights).
Fixes #3688
Fixes #2599
=> Reduces the maximum flow for internal infill to 3x nozzle diameter

lib/Slic3r/GUI/Plater/ObjectSettingsDialog.pm
Because of issue #1300 , I also see labels that are cut off:
This pull request fixes the cut off text on the object settings dialog:
=> Use default size for label and size column label to fit content.

lib/Slic3r/GUI/PresetEditor.pm, lib/Slic3r/Print/SupportMaterial.pm, slic3r.pl, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp, xs/src/libslic3r/PrintObject.cpp
Also a bug has been fixed for zero interface layers. Before
slic3r would put infinite number of interface layers over top surfaces,
if the number of interface layers was set to zero.
Fixes #3310 
Fixes #2757
Thanks to @bubnikv for this work.
Win32 automatic development build: https://bintray.com/lordofhyphens/Slic3r/Slic3r_Branches/1.3.0-infill-over-plate-192#files
=> A new feature "support_material_buildplate_only" implemented.

README.md, slic3r.pl
Option `--no-plater` is unknown since merge `gui3` branch, so it mus be removed from `slic3r.pl` and `README.md`.
=> Remove unused --no-plater option

lib/Slic3r/GUI/MainFrame.pm
which hides settings from PresetEditor but leaves Controller tab always visible
=> Fix regression from 35fc1de

package/linux/make_archive.sh
Decouples from the build system more and makes things easier to change versions.
=> On travis build server, use build wxlibs and not ubuntu system libs

xs/Build.PL
Permits augmenting CFLAGS to add possibly necessary LDFLAGS and CXXFLAGS/CFLAGS entries to our build script.
Less need to modify xs/Build.PL to enable/disable debugging, etc (can build debug builds from the build server now if desired)
=> Add environment CFLAGS, CXXFLAGS, and LDFLAGS to xs/Build.PL flags.

lib/Slic3r/GUI/Plater/ObjectPartsPanel.pm, lib/Slic3r/GUI/Plater/ObjectSettingsDialog.pm, xs/xsp/Model.xsp
Can now resize and rotate modifier meshes. Accessed through the right-click menu (similar to plater).
Fixes #3875.
=> Resize & Rotate modifier mesh

slic3r.pl
I frequently use the --datadir option to maintain different profiles or test settings from other people and have to point people to the [documentation](http://manual.slic3r.org/configuration-organization/configuration-organization) because the option is not listed in the command line info and most people don't know about it.
This PR only adds a short description of this option.
=> Command line help for --datadir option

lib/Slic3r/GUI/MainFrame.pm, lib/Slic3r/GUI/Plater.pm
Plater menu has no sense to be enabled when there are no objects in plater, so this patch enable/disable it when objects list is changed.
=> Disable Plater menu when there are no objects in plater

lib/Slic3r/GUI/Plater/2DToolpaths.pm, lib/Slic3r/GUI/Plater/3DPreview.pm
Fixes #3792 by skipping event handling in  3D Preview and Layer tabs when no `UP` or `DOWN` key is pressend.
=> Skip event handling in 3D/Layer preview tab when no UP or DOWN key is pressed

lib/Slic3r/GUI.pm, lib/Slic3r/GUI/Plater/OverrideSettingsPanel.pm, lib/Slic3r/GUI/PresetEditor.pm
In wxWidgets documentation there are three ways to set the size of the
scrolling area. The most automatic (and newest) way is by using SetScrollRate:
* http://docs.wxwidgets.org/trunk/classwx_scrolled.html#details
Also, change the anoying behavior of 1px per mouse step, which makes scrolling eternal, with a more comfortable font size related step rate.
It works as expected in GNU/Linux platform. Testing in Mac/Windows are welcome.
=> Enhance scrolling by using font point size as scroll rate

lib/Slic3r/GUI.pm
When in wxGTK (GNU/Linux), some widgets has a hardcoded point size font that not fit with normal GUI font and therefore this widgets doesn't inherit changes in system font size.
This commit only affect this platform, changing `!&Wx::wxMSW` to `&Wx::wxMAC`.
=> Remove hardcoded font size for wxGTK

.travis.yml, package/deploy/sftp.sh, xs/Build.PL
Attempting to link to libstdc++ statically to deal with relatively ancient systems (see: opensuse 13.2) which are never getting a more modern compiler than GCC 4.8.
@azalanono Fixes #4015
=> Link to libstdc++ statically.

lib/Slic3r/GUI/Plater.pm
`host_type` values are lowercase. This fixes a 404 error (because it attempts to
upload to /rr_upload) when sending G-code to Octoprint.
=> Fix host_type comparison when sending G-code to octoprint

package/common/coreperl, package/linux/make_archive.sh, package/osx/make_dmg.sh
Linux builds broke for a while because Storable wasn't necessarily available. So let's move the core perl modules we're packaging to one list instead of two (DRY).
=> Refactor out the perl packages into a common file.

README.md, xs/src/libslic3r/PrintConfig.cpp
This PR contains these fixes:
- add `--bed-shape` cli argument and add it to the doc
- make `--has-heatbed` compatible with other cli arguments and add it to the doc.
=> Fix some cli arguments

Build.PL, xs/Build.PL
While trying to build Slic3r for NixOS I noticed that it fails for older versions of ExtUtil::ParseXS and ExtUtil::XSpp.  I would recommend to update the required versions.  These versions are the ones that recent Travis CI build seem to be using
=> Update required ParseXS and XSpp versions

xs/src/libslic3r/Config.cpp
**Problem:**
Backslashes were not escaped during serialization by *escape_string_cstyle()*. If the backslash is located at the end of the string the next call to *unescape_string_cstyle()* detects a backslash without another character following and returns false. This terminates slic3r.
**Solution:**
Backslashes are now escaped and *unescape_string_cstyle()* will not fail anymore.
=> Fix for issue #4021 - Crash due to backslash at end of text fields for Custom G-code

lib/Slic3r/GUI/Plater/ObjectPartsPanel.pm
Re-added the ability to move part meshes relative to another part mesh in the same object.
Fixes #4118
=> Move part meshes around in Object Settings.

lib/Slic3r/Print/SupportMaterial.pm
fix for #4054
Currently, slic3r does not generate support for very thin hovering surfaces. This PR fixes the issue. See the [link](https://www.dropbox.com/s/mecr68mqw035wrb/Grand%20Snaget-Jofo%20%281%29.stl?dl=0) for an example model.
=> Fix generating supports for very thin hovering slices

xs/src/libslic3r/PrintConfig.hpp
Just replaced tabs with spaces in two lines for cleaner code. No side effects.
=> Fixes tab/space artefact from adaptive-slicing merge

xs/src/admesh/portable_endian.h, xs/src/admesh/stlinit.c
This PR flips the byte order to the host byte order while reading floats and uint32_t's from binary STLs.
Fix from https://github.com/admesh/admesh/pull/26
Closes: https://github.com/prusa3d/Slic3r/issues/532
Related PR: https://github.com/prusa3d/Slic3r/pull/534
=> Fix importing of binary STLs in big-endian architectures

xs/src/libslic3r/GCodeWriter.cpp
This PR fixes acceleration gcode for `reprap` flavor as the documentation stated http://reprap.org/wiki/G-code#M204:_Set_default_acceleration & https://duet3d.com/wiki/G-code#M201:_Set_max_acceleration
=> Fix acceleration gcode for RepRapFirmware

lib/Slic3r/GUI/Plater/ObjectSettingsDialog.pm
While updating the manual page for adaptive slicing (https://github.com/alexrj/Slic3r-Manual/issues/43) I realized that two object-settings tabs name `Adaptive Layers` and `Layers` might be confusing. Also the inline documentation of the `Layers` tab is somewhat outdated. Setting a range to height=0 to skip layers doesn't work anymore, I don't know when it was disabled, but at least since the latest stable 1.29 it doesn't work. It is explicitly checked that the heights are > 0. And I think the feature was not very useful anyway, since we have the cut dialog.
=> Better names / description of Layers object-settings tab

xs/src/boost/nowide/cenv.hpp
This error is encountered while compiling on `gcc version 7.1.0 (x86_64-posix-seh, Built by strawberryperl.com project)`
`ISO C++ forbids comparison between pointer and integer [-fpermissive]`
This PR fixes the error.
Issue on original repository: https://github.com/artyom-beilis/nowide/issues/22
=> Fix comparison bw integer and pointer

xs/src/libslic3r/GCodeTimeEstimator.cpp
I have been testing time estimation for about a week, it works pretty accurate with small models but the estimation for big and rounded models are very far (sometimes for days) from the expected.
Because generally the rounded models (means lots of gcode for a single line) are inaccurate, it looks like short displacement time calculation does not work well. So I considered constant speed for too short displacements and the results are really promising.
Time estimation is much more complex than it seems but this PR improves it a little bit.
=> Use constant speed for too short displacements

lib/Slic3r/GUI/PresetEditor.pm, lib/Slic3r/Print/Object.pm, t/support.t, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp, xs/src/libslic3r/PrintObject.cpp
Currently, slic3r uses `support_material_extrusion_width` for interfaces. Assigning very low values to `support_material_extrusion_width` makes supports very easy to break which is very a good feature. But when `support_material_extrusion_width` is very low, interfaces don't stick to neither the lower support layers nor the adjacent extrusion lines.
So what I do is to define a new configuration parameter for support material interfaces, and I can still use very low values `support_material_extrusion_width` and higher values for support material interfaces for reliable extrusion. For example:
For `nozzle_diameter = 0.4`;
`support_material_extrusion_width = 0.4` makes the supports very thin and easy to break and
`support_material_interface_extrusion_width = 0.5` makes reliable and accurate …
=> New configuration for support material interface extrusion width

lib/Slic3r/GUI.pm, lib/Slic3r/GUI/Plater.pm, lib/Slic3r/GUI/Preferences.pm
This adds a new preference to turn off auto alignment on the z axis (z=0). This can be useful when the input file already contains the correct z-axis location, as discussed here: https://github.com/alexrj/Slic3r/issues/404#issuecomment-349438749
=> Auto align z preference

lib/Slic3r/GUI/Plater/ObjectPartsPanel.pm
When autocentering is turned off the modifiers have to be aligned to the centre of the part.
=> Ensure that modifiers are aligned to the center of the part.

lib/Slic3r/Print/GCode.pm, xs/src/libslic3r/ConditionalGcode.hpp, xs/src/libslic3r/GCode.cpp, xs/src/libslic3r/GCode.hpp, xs/src/libslic3r/PrintConfig.cpp
In the current version, the conditional gcode parser doesn't apply to tool change G-codes, which is a major drawback (at least in my use-cases).
This PR executes the conditional parser for every toolchange.
I had to add an include guard to `ConditionalGcode.hpp` since it is already included via XS, otherwise it is a one-liner.
=> apply conditional gcode parser to tool change gcode

lib/Slic3r/GUI/MainFrame.pm
This fixes the following issue:
The close button for the first profile editor tab is not shown if "Display profile editors as tabs" is enabled and "Show Controller Tab" is disabled (in File -> Preferences...).
=> show close button for the first profile editor tab if controller tab is disabled

lib/Slic3r/GUI/Plater.pm
This places the following two warnings into the status bar: 
> "Your object appears to be too large, so it was automatically scaled down to fit your print bed."
> "Some of your object(s) appear to be outside the print bed. Use the arrange button to correct this." 
This is less obtrusive than the dialog box.
=> Use status bar to show warnings instead of obtrusive dialog box

lib/Slic3r/GUI/PresetEditor.pm, package/linux/appimage.sh, package/linux/libpaths.appimage.txt, xs/src/libslic3r/GCodeWriter.cpp, xs/src/libslic3r/GCodeWriter.hpp, xs/t/21_gcode.t
This is in the spec for both repetier and marlinfw.
Implements #4106 
Test checks for output from gcode->retract().
=> Long retract support in marlin and repetier for FW retract.

lib/Slic3r/GUI/2DBed.pm, lib/Slic3r/GUI/3DScene.pm, lib/Slic3r/GUI/ColorScheme.pm, lib/Slic3r/GUI/Plater/2D.pm, lib/Slic3r/GUI/Plater/2DToolpaths.pm, lib/Slic3r/GUI/Plater/3DPreview.pm, lib/Slic3r/GUI/Plater/SplineControl.pm, lib/Slic3r/GUI/Preferences.pm
Added an optional color scheme ([solarized](http://ethanschoonover.com/solarized)) to Slic3r.
See option in `Files` -> `Preferences` -> `Color Scheme`.
=> Solarized Color Scheme

lib/Slic3r/GUI/ColorScheme.pm, lib/Slic3r/GUI/Plater/2D.pm, lib/Slic3r/GUI/Plater/2DToolpaths.pm
Wrong default colors for:
* 2d platter step perimeter and infill
* selection if instances where present
See here:
https://github.com/alexrj/Slic3r/issues/4352
Thanks for reporting.
=> Wrong colors in 2d platter and instance color missing

lib/Slic3r/Print.pm
This is a solution to #4000.
I didn't realize this before I finished, but #4325 also solves the issue (it did remind me that \ is a poor escaping character for windows). However, that solution prevents ! from being using in any of the arguments or executable name. This one instead splits on whitespace and allows escaping whitespace so it doesn't prevent any filename from being expressed.
Examples:
`/path/to/executable` becomes `/path/to/executable` with the arg `outputfilename.gcode`
`/path/to/executable -arg -arg2` becomes `/path/to/executable` with args `-arg`, `-arg2`, and `outputfilename.gcode`
`/path/to/executable! with! spaces -arg -arg2` becomes `/path/to/executable with spaces` with args `-arg`, `-arg2`, and `outputfilename.gcode`
`/path/to/executable!! -arg -arg2` becomes …
=> Post-Processing Script Parameters

lib/Slic3r/Print/SupportMaterial.pm
Added changes suggested by @GregoryNoel that alternates interface layers by 90 degrees (each layer) which improves layer support.
Changes can be seen when viewing interface layers in the layer preview for a given object (set interface layers >1).
=> Raft pattern angles (#3001)

lib/Slic3r/GUI.pm, lib/Slic3r/GUI/Plater.pm, lib/Slic3r/GUI/Plater/ObjectPartsPanel.pm, lib/Slic3r/GUI/Preferences.pm, lib/Slic3r/GUI/ReloadDialog.pm, xs/src/libslic3r/Model.cpp, xs/src/libslic3r/Model.hpp, xs/xsp/Model.xsp
The function now tries to reload all referenced files (original object and added parts and modifiers) and asks the user how to proceed.
In the issue some opinions were given, that the function should discard all manual configurations (as 3mf files already contain them), and some that it should keep them (working with multiple exported STLs).
Additionally, warnings are thrown, if the reload doesn't work (original file deleted, object cut/ split) or added parts/ modifiers loose their reference to the path (modifier file deleted, less volumes in file -> the mesh is copied in that case).
**Plater.pm**
function load_file: pass the correct object index
set variables in the volumes to determine their origin
function reload_from_disk: see description
**ObjectPartsPanel.pm**
set variables in the …
=> "Reload from disk" - UI function overhaul

lib/Slic3r/GUI/Plater/SplineControl.pm, xs/src/libslic3r/PrintObject.cpp
Potential fix for #4255 
Try to match object top by reducing / increasing thickness of last layer after adaptive layer generation.
Should not brake anything, but I'd like to get feedback whether or not this is useful before merging.
=> Match object top

xs/src/libslic3r/Fill/FillGyroid.cpp, xs/src/libslic3r/Fill/FillGyroid.hpp
contains a bugfix for #4406
thanks to  bubnikv for the refactoring
note: for the "overlap", this pr does nothing, the bug is somewhere else in slic3r.
Iv'e tested with some stl, it slice and export gcode. But i didn't had the time to test a real print with the generate gcode. But it shouldn't be a problem.
=> merge FillGyroid to slic3rPe state

src/CMakeLists.txt
When using the libslic3r c++ code only via cmake and make commands the following error is obtained.
```Console
Undefined symbols for architecture x86_64:
"vtable for Slic3r::FillGyroid", referenced from:
Slic3r::FillGyroid::FillGyroid() in liblibslic3r.a(Fill.cpp.o)
NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [slic3r] Error 1
make[1]: *** [CMakeFiles/slic3r.dir/all] Error 2
make: *** [all] Error 2
```
=> Fix linker error due to absence of FillGyroid.cpp in CMakeLists.txt

lib/Slic3r/Print/GCode.pm, xs/src/libslic3r/GCodeWriter.cpp
activated with "verbose gcode" option
note: you didn't need to recompile GCodeWriter.cpp if you set "use relative E distance"
=> CancelObject implementation

xs/src/libslic3r/ExPolygon.cpp, xs/src/libslic3r/ExPolygon.hpp, xs/src/libslic3r/PerimeterGenerator.cpp
* no more strange turn at end => fusion of voronoi end lines when they are near enough
* anchoring inside the perimeters => extends the lines end inside the perimeter to join it. A gui parameter can be created to adjust it if needed (currently, it extends to meet the center).
* conservation of too small segments of thin walls when they are crossing each other => modification of the fusion algorithm to select the most strait path instead of a random one
=> thinwall improvements

xs/src/tiny_obj_loader.h
This fixes a security vulnerability caused by `std::sscanf()` calls.
(Thanks Alexander Kuntschik for the report)
=> Update tiny_obj_loader.h to latest version

translation/de_DE.po, translation/en_US.po, translation/fr_FR.po, translation/zh_CN.po, xs/src/libslic3r/PrintConfig.cpp
Recommend merging if only to avoid headaches later (and give a heads-up to people adding options that they need to wrap strings in libslic3r with the macro for things to work). 
I think that the branch should stay up to collect translations (provide another PR when they are known to work). 
I am unsure if we should include the compiled files here in the repository or run a script over them to generate them during the build process.
=> Added translation string markers to libslic3r PrintConfig text.

xs/src/libslic3r/Print.cpp
**Error**: The forward declaration of std::ofstream (used in export_gcode) caused the error below:
`/Slic3r/xs/src/libslic3r/Print.cpp: In member function ‘void Slic3r::Print::export_gcode(const string&, bool)’:
/Slic3r/xs/src/libslic3r/Print.cpp:723:36: error: variable ‘std::ofstream outstream’ has initializer but incomplete type
std::ofstream outstream(outfile);`
**Solution**: Include `<fstream>`
=> FIX: Forward declaration of std::ofstream caused CMake to abort

src/slic3r.cpp, xs/src/libslic3r/ConfigBase.cpp, xs/src/libslic3r/ConfigBase.hpp, xs/src/libslic3r/PrintConfig.cpp, xs/src/libslic3r/PrintConfig.hpp
In response to what was discussed [here](https://github.com/slic3r/Slic3r/issues/4509#issuecomment-414833202) and what was suggested, I've decided to make some modifications to add coherence.
1. Previously, `print_cli_options`only printed the options related to **printing**. I was find it very confusing to use the CLI as the options weren't listed. I've renamed it to `print_print_options`.
2. Now, in addition to that options, I've added the CLI options (which is basically a copy of the previous function calling out CliConfigDef options). I've attached the resulting usage file for convenience.
3. I was finding it strange and confusing (at least as a user) that if an unsupported option is entered as CLI's input, it will only issue a warning and continue processing. As such, I've made …
=> Print CLI options in addition to the print ones

lib/Slic3r/GUI/Plater.pm
On HiDPI screens, the button height set to 30px will cause buttons of limited height with parts of the text cut off. Setting the height to `-1` seems to fix this so the buttons work fine.
=> Auto-determine right pane button height.

xs/src/admesh/stl.h
admesh works fine on little-endian machines as of b9592961. It just doesn't
compile because of this pesky #error.
=> Drop #error "admesh works correctly on little endian machines only"

src/CMakeLists.txt
Separate out include directories to cover each sublibrary to avoid triggering builds for (mostly static) sublibraries.
=> CMakeLists refactor

src/CMakeLists.txt, src/test/libslic3r/test_log.cpp, xs/src/libslic3r/Log.cpp, xs/src/libslic3r/Log.hpp
I've added basic filtering capabilities based on log level and topic name to Slic3r::Log. 
This review is primarily for usability questions; getting added next is basic file redirection and making output of ExtrusionEntities via SVG easy to command. I'm open for ideas for more things to log. 
This includes tests for the std::string system (std::wstring is converted based on locale).
=> Expanding Slic3r::Log

src/CMakeLists.txt, src/test/libslic3r/test_log.cpp, xs/src/libslic3r/Log.cpp, xs/src/libslic3r/Log.hpp
As #4604 was merged by mistake, re-creating PR.
Changes:
Use boost::locale instead of corecvt.  
Note: "Revert Revert" is required because the previous reversion deleted files which confuses git when trying to merge later.
I suggest using squash + merge when merging PRs that are only reversions; it should provide a clean baseline.
=> Slic3r::Log 

lib/Slic3r/GUI.pm, lib/Slic3r/GUI/ColorScheme.pm, lib/Slic3r/GUI/Plater.pm, lib/Slic3r/GUI/Preferences.pm
I think the idea proposed in #4419 is great, as power users need advanced and flexible controls for manipulating models. Slic3r definitely needs to be very customizable in the long term so that every user can adapt it to their preferred workflow. As of now we don't have customizable palettes or other things like this, so the idea proposed by @foreachthing is a great start.
I think we can achieve the same goal by simplifying it a bit. I understand @foreachthing did it fully customizable in order to make sure his Pull Request was merged :-) and now I think we can improve over that.
Here I'm proposing the following changes:
* **always** have the *Rotate by 180°* commands in the contextual menu item (no need to make this configurable)
* No need to show the *Rotate Z 90°* buttons in the …
=> Rename "Extended GUI" to "Rotation controls" and simplify it

.travis.yml, package/linux/travis-build-main.sh
Looks like if a dependent script fails, Travis will happily report everything is fine because the if statement completed. These changes should ensure that a return code is propagated up and travis is terminated if the return code comes back with an error.
Reference: http://steven.casagrande.io/articles/travis-ci-and-if-statements/
=> Ensure that travis reports failure if build/tests fail

src/test/libslic3r/test_flow.cpp, xs/src/libslic3r/Flow.cpp
In some situations the calculated solid spacing can be 0 with first-layer  widths of ~0.41mm and a requested brim connection width of 1mm, even though the actual spacing is nonzero.
Add a test case to flow test suite to cover this situation.
Fixes #4654
=> Fix edge case in spacing calculation for solid spacing.

.travis.yml, package/linux/appimage-apprun.sh, package/linux/appimage.sh, package/linux/build_shell.mk, package/linux/libpaths.appimage.txt, package/linux/travis-build-main.sh, xs/src/libslic3r/ConfigBase.hpp, xs/src/libslic3r/GCodeSender.hpp
Update travis build items to use gcc8 instead of gcc4.9
Fixes #4664
=> Use GCC8 instead of 4.9 for travis

src/test/libslic3r/test_config.cpp, xs/src/libslic3r/ConfigBase.hpp
coBool options weren't permitted to be set with boolean values; the only valid setter was via string "1" and "0", which is very inconvenient (and wasn't intended on the initial PR). 
Additionally, booleans being set with a string are a special kind of enumeration and should be treated as such. Our configs emit "1" and "0" and should not accept "Z" or anything like that (which they were and treating as false). 
Tests have been fixed/expanded.
=> Permit coBool options to be set with booleans

src/test/libslic3r/test_print.cpp, xs/src/libslic3r/PrintObject.cpp
Invalidate posDetectSurfaces during make_perimeters() when posSlice would also get invalidated.
Can't use invalidate_step() as that invalidates the perimeters as well.
Fixes #4620
=> Patch for #4620 - ensure posDetectSurfaces is invalidated on slice change

README.md
=> README.md:fix typo under directory structure section

src/CMakeLists.txt, src/test/libslic3r/test_polygon.cpp, xs/src/libslic3r/ExPolygon.cpp, xs/src/libslic3r/ExPolygon.hpp, xs/src/libslic3r/Point.cpp, xs/src/libslic3r/Point.hpp, xs/src/libslic3r/Polygon.cpp, xs/src/libslic3r/Polygon.hpp, xs/src/libslic3r/PrintObject.cpp, xs/src/libslic3r/SurfaceCollection.cpp, xs/src/libslic3r/SurfaceCollection.hpp
Fixes #4726.
collinear lines are removed from the `slices` polygons of each layer (parallelized).
This could potentially also be implemented in the [make_loops](https://github.com/slic3r/Slic3r/blob/master/xs/src/libslic3r/TriangleMesh.cpp#L1135) method where the polygons from slicing are assembled, not sure if that would gain any performance.
Includes a simple CATCH testcase, but only for the remove_collinear_points part of Polygon.
=> Simplify collinear points

package/linux/startup_script.sh, package/osx/startup_script.sh
Without quotes, no matter how you quote or escape the paths, it's not possible to pass STL files with spaces in their paths:
```
$ Slic3r "/path/to/STL files/foo.stl"
Error while opening /path/to/STL: Unknown file format
$ Slic3r /path/to/STL\ files/foo.stl 
Error while opening /path/to/STL: Unknown file format
```
=> Add missing quotes to startup scripts

.github/CONTRIBUTING.md, README.md
This is to help with https://github.com/slic3r/website/issues/3
[skip ci]
=> consolidate contributing information

package/linux/appimage.sh
fixes #4721 
Changes the icon used for Linux `.appimage` builds to `/var/Slic3r_192px.png` instead of `/var/Slic3r_192px_transparent.png`
=> fix transparent desktop icon

package/linux/travis-build-main.sh, src/CMakeLists.txt, src/test/libslic3r/test_gcode.cpp, src/test/libslic3r/test_gcodewriter.cpp, xs/src/libslic3r/GCode/CoolingBuffer.cpp, xs/src/libslic3r/GCode/CoolingBuffer.hpp, xs/src/libslic3r/GCodeWriter.cpp
Includes test.
Fixes #4769
Duplicates #4770 because could not check branch out of just number names.
=> Restrict speed setting to fixed-point output with 3 decimal places.

lib/Slic3r/GUI/Preset.pm, xs/src/libslic3r/ConfigBase.cpp, xs/src/libslic3r/Log.hpp
If a loaded config.ini has a parse error from boost::property_tree::read_ini, handle things a little more gracefully.
Fixes #4724
=> Catch and rethrow parse errors, showing a log entry and a GUI error.

src/CMakeLists.txt, src/test/libslic3r/test_printobject.cpp, xs/src/libslic3r/PrintObject.cpp
The algorithm used to adjust layer heights in PrintObject has as a ceiling some default values that were fine when nozzles were < 1.0mm but not anymore.
To avoid more surprises, set to numeric_limits<double>::max()
Adds regression test as well.
Fixes #4516
=> Set the initial maximum size for layer heights and nozzle diameter to max

src/CMakeLists.txt, src/test/libslic3r/test_extrusion_entity.cpp, xs/src/libslic3r/ExtrusionEntityCollection.cpp, xs/src/libslic3r/ExtrusionEntityCollection.hpp, xs/src/libslic3r/PrintGCode.cpp
Responding to comments in 6710b24 by @bubnikv and incorporating suggested changes made by @supermerill from #4553 as a single function with a flag instead of two methods.
=> Allow for flattening with and without sort.

xs/src/libslic3r/ExPolygon.cpp, xs/src/libslic3r/Fill/FillPlanePath.cpp, xs/src/libslic3r/IO/AMF.cpp, xs/src/libslic3r/SurfaceCollection.cpp
- Removed un-used variables.
- Fixed some comparisons with signed / unsigned variables
There are still warnings but solving them would require to change `PrintConfig` (derives from`GCodeConfig`) and I'm not familiar with the code base so I didn't try anything.
=> Solve some compilation warnings in libslic3r

lib/Slic3r/GUI/PresetEditor.pm
Bridge speed is still used when overhang perimeters are present, which means that it cannot be disabled if there is no infill. 
Fixes #4842
=> Don't disable bridge_speed in GUI when no infill configured.

src/test/libslic3r/test_printgcode.cpp, xs/src/libslic3r/PrintGCode.cpp
Fix for #4830.  
Tested by compiling the C++ binary and running:
`slic3r --gcode --load config.ini -m --dont-arrange <first stl> <second stl>`
where _config.ini_ contains 
`layer_gcode = ;Layer:[layer_num] ([layer_z] mm)`
When examining the output gcode, the _layer_num_ value will increase with layer_z.
=> Change [layer_num] to use layer.id()

lib/Slic3r/GUI/Plater.pm
Display the approximate print time of the sliced object(s) in
“hour, minutes and seconds” instead of “minutes and seconds”.
=> Display approx. print-time in hours

xs/Build.PL
The `__STRICT_ANSI__` macro is defined by the compiler and you should not undefine or redefine it.
Using `-U__STRICT_ANSI__ -std=c++11` is just silly. If you don't want strict mode, don't ask for strict mode. Certainly don't ask for strict mode and then undefined the macro that is defined by strict mode.
The correct solution is `-std=gnu++11` which doesn't define the macro in the first place.
=> Do not undefine __STRICT_ANSI__

src/CMakeLists.txt
According to https://github.com/microsoft/vcpkg/issues/5936#issuecomment-479577971 Boost 1.70+ ships with their own cmake configuration, which is tried to be used. This failed the cmake configuration in Ubuntu 20.04 LTS with Boost 1.71.0 installed on the system unless this change is present.
Confirmed resolving building issues for the above system (Ubuntu 20.04 LTS / Boost 1.71.0)
Build still working for Windows (Win 10 64-bit / Boost 1.63.0), although I'm not sure whether this CMakeList is invoked then.
=> cmake - Boost 1.70+ compatibility

src/CMakeLists.txt, src/slic3r.cpp, xs/src/libslic3r/Layer.cpp
Automatically log at the DEBUG level if this is done.
Fix compile issue where Log.hpp wasn't available.
=> Allow for compiling with debug output turned on by default.

src/test/libslic3r/test_printobject.cpp, xs/src/libslic3r/PrintObject.cpp
Throw a runtime error if the number of solid layers grows above the total possible layers.
Edit the loop syntax to need the current shell thickness to be less than the minimum to add more layers (avoid infinite loop).
Add test to cover normal operation and regression for this layer arrangement.
Fixes #5019
=> Fix issue around infinite loop in min vertical shells.
